//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkirKendaraan.TransaksiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaksi", Namespace="http://schemas.datacontract.org/2004/07/WebService.Model")]
    [System.SerializableAttribute()]
    public partial class Transaksi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdKategoriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoPolisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TanggalKeluarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TanggalMasukField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdKategori {
            get {
                return this.IdKategoriField;
            }
            set {
                if ((this.IdKategoriField.Equals(value) != true)) {
                    this.IdKategoriField = value;
                    this.RaisePropertyChanged("IdKategori");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoPolisi {
            get {
                return this.NoPolisiField;
            }
            set {
                if ((object.ReferenceEquals(this.NoPolisiField, value) != true)) {
                    this.NoPolisiField = value;
                    this.RaisePropertyChanged("NoPolisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TanggalKeluar {
            get {
                return this.TanggalKeluarField;
            }
            set {
                if ((this.TanggalKeluarField.Equals(value) != true)) {
                    this.TanggalKeluarField = value;
                    this.RaisePropertyChanged("TanggalKeluar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TanggalMasuk {
            get {
                return this.TanggalMasukField;
            }
            set {
                if ((this.TanggalMasukField.Equals(value) != true)) {
                    this.TanggalMasukField = value;
                    this.RaisePropertyChanged("TanggalMasuk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kategori", Namespace="http://schemas.datacontract.org/2004/07/WebService.Model")]
    [System.SerializableAttribute()]
    public partial class Kategori : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HargaJamPertamaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long HargaPerJamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeteranganField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HargaJamPertama {
            get {
                return this.HargaJamPertamaField;
            }
            set {
                if ((this.HargaJamPertamaField.Equals(value) != true)) {
                    this.HargaJamPertamaField = value;
                    this.RaisePropertyChanged("HargaJamPertama");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long HargaPerJam {
            get {
                return this.HargaPerJamField;
            }
            set {
                if ((this.HargaPerJamField.Equals(value) != true)) {
                    this.HargaPerJamField = value;
                    this.RaisePropertyChanged("HargaPerJam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Keterangan {
            get {
                return this.KeteranganField;
            }
            set {
                if ((object.ReferenceEquals(this.KeteranganField, value) != true)) {
                    this.KeteranganField = value;
                    this.RaisePropertyChanged("Keterangan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransaksiService.ITransaksiService")]
    public interface ITransaksiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/FetchAllTransaksi", ReplyAction="http://tempuri.org/ITransaksiService/FetchAllTransaksiResponse")]
        ParkirKendaraan.TransaksiService.Transaksi[] FetchAllTransaksi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/FetchAllTransaksi", ReplyAction="http://tempuri.org/ITransaksiService/FetchAllTransaksiResponse")]
        System.Threading.Tasks.Task<ParkirKendaraan.TransaksiService.Transaksi[]> FetchAllTransaksiAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/InsertNewTransaksi", ReplyAction="http://tempuri.org/ITransaksiService/InsertNewTransaksiResponse")]
        bool InsertNewTransaksi(string noPolisi, long idKategori, System.DateTime tanggalMasuk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/InsertNewTransaksi", ReplyAction="http://tempuri.org/ITransaksiService/InsertNewTransaksiResponse")]
        System.Threading.Tasks.Task<bool> InsertNewTransaksiAsync(string noPolisi, long idKategori, System.DateTime tanggalMasuk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/UpdateTransaksi", ReplyAction="http://tempuri.org/ITransaksiService/UpdateTransaksiResponse")]
        bool UpdateTransaksi(long id, string noPolisi, long idKategori, System.DateTime tanggalMasuk, System.DateTime tanggalKeluar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/UpdateTransaksi", ReplyAction="http://tempuri.org/ITransaksiService/UpdateTransaksiResponse")]
        System.Threading.Tasks.Task<bool> UpdateTransaksiAsync(long id, string noPolisi, long idKategori, System.DateTime tanggalMasuk, System.DateTime tanggalKeluar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/DeleteTransaksi", ReplyAction="http://tempuri.org/ITransaksiService/DeleteTransaksiResponse")]
        bool DeleteTransaksi(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/DeleteTransaksi", ReplyAction="http://tempuri.org/ITransaksiService/DeleteTransaksiResponse")]
        System.Threading.Tasks.Task<bool> DeleteTransaksiAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/FetchKategori", ReplyAction="http://tempuri.org/ITransaksiService/FetchKategoriResponse")]
        ParkirKendaraan.TransaksiService.Kategori FetchKategori(long idKategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/FetchKategori", ReplyAction="http://tempuri.org/ITransaksiService/FetchKategoriResponse")]
        System.Threading.Tasks.Task<ParkirKendaraan.TransaksiService.Kategori> FetchKategoriAsync(long idKategori);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/FetchAllKategori", ReplyAction="http://tempuri.org/ITransaksiService/FetchAllKategoriResponse")]
        ParkirKendaraan.TransaksiService.Kategori[] FetchAllKategori();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransaksiService/FetchAllKategori", ReplyAction="http://tempuri.org/ITransaksiService/FetchAllKategoriResponse")]
        System.Threading.Tasks.Task<ParkirKendaraan.TransaksiService.Kategori[]> FetchAllKategoriAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransaksiServiceChannel : ParkirKendaraan.TransaksiService.ITransaksiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransaksiServiceClient : System.ServiceModel.ClientBase<ParkirKendaraan.TransaksiService.ITransaksiService>, ParkirKendaraan.TransaksiService.ITransaksiService {
        
        public TransaksiServiceClient() {
        }
        
        public TransaksiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransaksiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaksiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransaksiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ParkirKendaraan.TransaksiService.Transaksi[] FetchAllTransaksi() {
            return base.Channel.FetchAllTransaksi();
        }
        
        public System.Threading.Tasks.Task<ParkirKendaraan.TransaksiService.Transaksi[]> FetchAllTransaksiAsync() {
            return base.Channel.FetchAllTransaksiAsync();
        }
        
        public bool InsertNewTransaksi(string noPolisi, long idKategori, System.DateTime tanggalMasuk) {
            return base.Channel.InsertNewTransaksi(noPolisi, idKategori, tanggalMasuk);
        }
        
        public System.Threading.Tasks.Task<bool> InsertNewTransaksiAsync(string noPolisi, long idKategori, System.DateTime tanggalMasuk) {
            return base.Channel.InsertNewTransaksiAsync(noPolisi, idKategori, tanggalMasuk);
        }
        
        public bool UpdateTransaksi(long id, string noPolisi, long idKategori, System.DateTime tanggalMasuk, System.DateTime tanggalKeluar) {
            return base.Channel.UpdateTransaksi(id, noPolisi, idKategori, tanggalMasuk, tanggalKeluar);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateTransaksiAsync(long id, string noPolisi, long idKategori, System.DateTime tanggalMasuk, System.DateTime tanggalKeluar) {
            return base.Channel.UpdateTransaksiAsync(id, noPolisi, idKategori, tanggalMasuk, tanggalKeluar);
        }
        
        public bool DeleteTransaksi(long id) {
            return base.Channel.DeleteTransaksi(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTransaksiAsync(long id) {
            return base.Channel.DeleteTransaksiAsync(id);
        }
        
        public ParkirKendaraan.TransaksiService.Kategori FetchKategori(long idKategori) {
            return base.Channel.FetchKategori(idKategori);
        }
        
        public System.Threading.Tasks.Task<ParkirKendaraan.TransaksiService.Kategori> FetchKategoriAsync(long idKategori) {
            return base.Channel.FetchKategoriAsync(idKategori);
        }
        
        public ParkirKendaraan.TransaksiService.Kategori[] FetchAllKategori() {
            return base.Channel.FetchAllKategori();
        }
        
        public System.Threading.Tasks.Task<ParkirKendaraan.TransaksiService.Kategori[]> FetchAllKategoriAsync() {
            return base.Channel.FetchAllKategoriAsync();
        }
    }
}
